In [1]:
# config = {
#     'name_model' : 'vinai/phobert-base',
#     'max_length' : 256,
#     'device' : 'cuda',
#     'batch_size' : 16,
#     'drop_rate' : 0.2,
#     'num_classes' : 5,
#     'num_epochs' : 25,
#     'weights' : [0.2, 0.3, 0.2, 0.15, 0.15],
#     'type' : 'Hotel',
# }
# Restaurant Classification
# config = {
#     'name_model' : 'vinai/phobert-base',
#     'max_length' : 256,
#     'device' : 'cuda',
#     'batch_size' : 16,
#     'drop_rate' : 0.2,
#     'num_classes' : 5,
#     'num_epochs' : 10,
#     'weights' : [0.35, 0.35, 0.1, 0.1, 0.1],
#     'type' : 'Restaurant',
#     'seed' : 42,
#     'isKaggle' : False
# }
config = {
    'name_model' : 'uitnlp/visobert',
    'max_length' : 256,
    'device' : 'cuda',
    'batch_size' : 16,
    'drop_rate' :0.5,
    'num_classes' : 5,
    'num_epochs' :40,
    'weights' : [0.35, 0.35, 0.1, 0.1, 0.1],
    'type' : 'Restaurant',
    'seed' : 32,
    'isKaggle' : False
}

In [ ]:
from transformers import AutoTokenizer, AutoModel
name_model = 'uitnlp/visobert'
tokenizer = AutoTokenizer.from_pretrained(name_model)
model = AutoModel.from_pretrained(name_model)

In [36]:
tk = tokenizer('Xin chào các bạn', return_tensors='pt', max_length=256, padding='max_length', truncation=True)

In [42]:
hidden_states = model(input_ids = tk['input_ids'], attention_mask = tk['attention_mask'], output_hidden_states=True).hidden_states

In [43]:
import torch
pooler_output = torch.cat(
            tuple([hidden_states[i] for i in [-4, -3, -2, -1]]), dim=-1)

In [47]:
p = pooler_output[:, 0, :]
p

tensor([[ 0.0712, -0.0212,  0.0685,  ..., -0.0645,  0.1268,  0.3202]],
       grad_fn=<SliceBackward0>)

In [50]:
last_hidden_state, pooler_output = model(input_ids = tk['input_ids'], attention_mask = tk['attention_mask'], return_dict=False)

In [ ]:
# tokenizer('xin chào', max_length=256,
#             padding="max_length",
#             truncation=True,
#             return_tensors="pt")

In [2]:
from train import Instructor, InstructorVer2, InstructorVer3

c:\Users\thanh\anaconda3\envs\vlsp2018\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
ins = InstructorVer3(config)

Some weights of XLMRobertaModel were not initialized from the model checkpoint at uitnlp/visobert and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [4]:
ins.train()

c:\Users\thanh\anaconda3\envs\vlsp2018\Lib\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


Epoch : 1 / 40


100%|██████████| 554/554 [03:29<00:00,  2.64it/s]


Len Train Data :  8855
Losses Train : 0.5749945343853322


100%|██████████| 69/69 [00:09<00:00,  7.36it/s]


Len Val Data :  1100
Losses Validate : 0.4958917700160633
Epoch : 2 / 40


100%|██████████| 554/554 [03:30<00:00,  2.63it/s]


Len Train Data :  8855
Losses Train : 0.4167554063759302


100%|██████████| 69/69 [00:09<00:00,  7.34it/s]


Len Val Data :  1100
Losses Validate : 0.42007094036449083
Epoch : 3 / 40


100%|██████████| 554/554 [03:30<00:00,  2.63it/s]


Len Train Data :  8855
Losses Train : 0.3349377266503134


100%|██████████| 69/69 [00:09<00:00,  7.31it/s]


Len Val Data :  1100
Losses Validate : 0.3705640918558294
Epoch : 4 / 40


100%|██████████| 554/554 [03:31<00:00,  2.62it/s]


Len Train Data :  8855
Losses Train : 0.297825112442456


100%|██████████| 69/69 [00:09<00:00,  7.44it/s]


Len Val Data :  1100
Losses Validate : 0.35489661650224164
Epoch : 5 / 40


100%|██████████| 554/554 [03:34<00:00,  2.59it/s]


Len Train Data :  8855
Losses Train : 0.2675271856253057


100%|██████████| 69/69 [00:09<00:00,  7.32it/s]


Len Val Data :  1100
Losses Validate : 0.31491717143492265
Epoch : 6 / 40


100%|██████████| 554/554 [03:33<00:00,  2.59it/s]


Len Train Data :  8855
Losses Train : 0.2441522306940907


100%|██████████| 69/69 [00:09<00:00,  7.23it/s]


Len Val Data :  1100
Losses Validate : 0.3237455979260531
Epoch : 7 / 40


100%|██████████| 554/554 [03:34<00:00,  2.59it/s]


Len Train Data :  8855
Losses Train : 0.22681973037041223


100%|██████████| 69/69 [00:09<00:00,  7.13it/s]


Len Val Data :  1100
Losses Validate : 0.3051477594809099
Epoch : 8 / 40


100%|██████████| 554/554 [03:32<00:00,  2.61it/s]


Len Train Data :  8855
Losses Train : 0.2127221455485184


100%|██████████| 69/69 [00:09<00:00,  7.32it/s]


Len Val Data :  1100
Losses Validate : 0.28438674840060146
Epoch : 9 / 40


100%|██████████| 554/554 [03:33<00:00,  2.59it/s]


Len Train Data :  8855
Losses Train : 0.20315127519481535


100%|██████████| 69/69 [00:09<00:00,  7.16it/s]


Len Val Data :  1100
Losses Validate : 0.28004375501112505
Epoch : 10 / 40


100%|██████████| 554/554 [03:37<00:00,  2.55it/s]


Len Train Data :  8855
Losses Train : 0.19068189810252606


100%|██████████| 69/69 [00:09<00:00,  7.11it/s]


Len Val Data :  1100
Losses Validate : 0.2816114371473139
Epoch : 11 / 40


 31%|███       | 169/554 [01:05<02:29,  2.58it/s]


KeyboardInterrupt: 

In [7]:
# # key=['AMBIENCE', 'QUALITY', 'PRICES', 'LOCATION', 'SERVICE']
str = 'Ở đây cà phê ngon, rẻ, mát mẻ'

str2 = 'Đồ ăn ngon, phục vụ như lol'
# [1,1,1,0,0]
# [0,1,0,0,1]
# ins.prediction(str, True)
# ins.prediction(str2, True)
ins.prediction(str)
ins.prediction(str2)

c:\Users\thanh\Documents\GitHub\ABSA\train.py:666: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.model.load_state_dict(torch.load(


Model checkpoint loaded successfully.
[[0 1 1 0 0]]
Model checkpoint loaded successfully.
[[0 1 0 0 1]]
