In [1]:
from train_sentiment import *

c:\Users\thanh\anaconda3\envs\vlsp2018\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
import torch
import torch.nn as nn

In [9]:
a = torch.tensor([1, 2, 3])
a.unsqueeze(1).expand(-1, 4)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5]])

In [2]:
model = Instructor()

In [3]:
model.train()

Epoch : 1 / 7


  0%|          | 0/181 [00:00<?, ?it/s]

tensor([[0.2701, 0.1970, 0.2660, 0.2669],
        [0.2335, 0.1783, 0.2551, 0.3330],
        [0.2906, 0.2064, 0.2426, 0.2604],
        [0.2089, 0.1646, 0.2395, 0.3870],
        [0.2627, 0.2531, 0.2296, 0.2546],
        [0.2129, 0.2040, 0.2878, 0.2953],
        [0.2064, 0.1832, 0.2819, 0.3285],
        [0.1714, 0.1863, 0.2687, 0.3736],
        [0.2547, 0.1901, 0.2238, 0.3314],
        [0.2056, 0.1864, 0.2725, 0.3356],
        [0.2602, 0.1882, 0.2480, 0.3036],
        [0.2104, 0.1915, 0.2543, 0.3438],
        [0.2149, 0.1747, 0.2091, 0.4013],
        [0.2023, 0.2105, 0.2966, 0.2906],
        [0.2074, 0.2074, 0.2873, 0.2979],
        [0.2291, 0.2000, 0.2470, 0.3238]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)
tensor([[0.2167, 0.2647, 0.2750, 0.2435],
        [0.2287, 0.2599, 0.2581, 0.2534],
        [0.2347, 0.2506, 0.2236, 0.2910],
        [0.1701, 0.3390, 0.2354, 0.2555],
        [0.2986, 0.2353, 0.2419, 0.2241],
        [0.1873, 0.2602, 0.3053, 0.2472],
        [0.2344, 0.2715

TypeError: unsqueeze() missing 1 required positional arguments: "dim"

In [3]:
model.train()

Epoch : 1 / 7


  0%|          | 0/181 [00:00<?, ?it/s]

Softmax(
  dim=tensor([[ 0.0214, -0.2941,  0.0063,  0.0097],
          [-0.0914, -0.3610, -0.0028,  0.2636],
          [ 0.1294, -0.2124, -0.0511,  0.0197],
          [-0.2365, -0.4749, -0.0996,  0.3801],
          [ 0.0390,  0.0016, -0.0959,  0.0076],
          [-0.3107, -0.3532, -0.0093,  0.0164],
          [-0.2999, -0.4189,  0.0117,  0.1649],
          [-0.5925, -0.5090, -0.1426,  0.1870],
          [-0.0757, -0.3683, -0.2050,  0.1877],
          [-0.3895, -0.4874, -0.1078,  0.1007],
          [-0.0940, -0.4181, -0.1419,  0.0603],
          [-0.3068, -0.4010, -0.1177,  0.1840],
          [-0.0125, -0.2192, -0.0398,  0.6122],
          [-0.1810, -0.1412,  0.2016,  0.1813],
          [-0.2038, -0.2040,  0.1218,  0.1580],
          [-0.1890, -0.3248, -0.1139,  0.1568]], device='cuda:0',
         grad_fn=<AddmmBackward0>)
)
Softmax(
  dim=tensor([[-0.0819,  0.1182,  0.1564,  0.0346],
          [-0.0045,  0.1233,  0.1163,  0.0982],
          [-0.0153,  0.0500, -0.0639,  0.1997],
       

NameError: name 'pred' is not defined